import { SpeciesEntry } from './types';

export const ENCYCLOPEDIA_SPECIES: SpeciesEntry[] = [
  {
    id: 'vespa-velutina',
    common_name: 'Asian Hornet (Yellow-legged Hornet)',
    latin_name: 'Vespa velutina nigrithorax',
    category: 'Dangerous',
    danger_level: 8,
    can_sting: true,
    can_bite: true,
    dangerous_to_children: true,
    dangerous_to_pets: true,
    regions: ['UK', 'EU'],
    active_seasons: ['Spring', 'Summer', 'Autumn'],
    habitat: 'Tree canopies, hedgerows, human buildings, and apiaries.',
    description: 'Invasive predatory hornet with a velvety dark brown thorax, yellow tipped legs, and a prominent orange segment on the abdomen. Highly destructive predator of domestic honeybee colonies.',
    first_aid: 'Wash the sting thoroughly with soap and water. Apply an ice pack for 15 minutes. Take oral antihistamines. Seek emergency help if multiple stings occur or allergic signs appear.',
    when_to_call_emergency: 'Call emergency services (999/112) immediately if throat swelling, dizziness, or breathing issues occur, or if stung in the head/neck area.',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Vespa_crabro_01.jpg/800px-Vespa_crabro_01.jpg',
    look_alikes: ['European Hornet (Vespa crabro)', 'Giant Woodwasp (Urocerus gigas)'],
    fun_fact: 'Asian hornets are specialized predators of honeybees, hovering outside hives to capture returning foragers and carry them back to nourish developing larvae.',
    country_top_ten: [
      { country: 'UK', rank: 2, danger_summary: 'Major ecological invasive threat with potent defensive venom.' },
      { country: 'EU', rank: 3, danger_summary: 'Rapidly spreading invasive hornet causing severe allergic hospitalizations.' }
    ]
  },
  {
    id: 'atrox-robustus',
    common_name: 'Sydney Funnel-Web Spider',
    latin_name: 'Atrax robustus',
    category: 'Venomous',
    danger_level: 10,
    can_sting: false,
    can_bite: true,
    dangerous_to_children: true,
    dangerous_to_pets: true,
    regions: ['AU'],
    active_seasons: ['Summer', 'Autumn'],
    habitat: 'Moist sheltered burrows under logs, gardens, and swimming pool filtration boxes in Sydney basin.',
    description: 'One of the world’s most venomous arachnids. Stocky, dark brown to black glossy carapace with powerful downward-striking fangs containing delta-atracotoxin.',
    first_aid: 'Apply pressure immobilization bandage (PIB) firmly over the entire bitten limb. Keep patient completely still and quiet. Call 000 emergency services without delay.',
    when_to_call_emergency: 'Immediate ambulance dispatch (000 in Australia). Venom can cause systemic neurotoxic collapse within 15 to 30 minutes if left untreated.',
    photo_url: 'https://images.unsplash.com/photo-1546842931-886c185b4c8c?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['Mouse Spider (Missulena)', 'Trapdoor Spider (Idiopidae)'],
    fun_fact: 'Specific antivenom is available and can be highly effective when administered promptly. Suspected Sydney Funnel-Web bites remain medical emergencies requiring urgent medical treatment.',
    country_top_ten: [
      { country: 'AU', rank: 1, danger_summary: 'World-renowned medical emergency; bites require immediate antivenom.' }
    ]
  },
  {
    id: 'loxosceles-reclusa',
    common_name: 'Brown Recluse Spider',
    latin_name: 'Loxosceles reclusa',
    category: 'Venomous',
    danger_level: 9,
    can_sting: false,
    can_bite: true,
    dangerous_to_children: true,
    dangerous_to_pets: true,
    regions: ['US'],
    active_seasons: ['Spring', 'Summer', 'Autumn'],
    habitat: 'Undisturbed indoor closets, attics, cardboard boxes, crawlspaces, and woodpiles.',
    description: 'Tan to dark brown spider characterized by a distinctive violin-shaped mark on its cephalothorax and having 6 eyes arranged in pairs (dyads) rather than 8.',
    first_aid: 'Wash bite with antiseptic soap and water. Apply cold compress (10 min on, 10 min off). Elevate the limb. Seek prompt medical evaluation.',
    when_to_call_emergency: 'Visit Urgent Care or ER if the central bite area turns dark purple/black (necrosis) or if spreading ulceration, fever, or chills develop.',
    photo_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['Southern House Spider (Kukulcania)', 'Cellar Spider (Pholcidae)', 'Wolf Spider'],
    fun_fact: 'Brown recluse spiders are nocturnal and prefer flight over fight; most bites occur when someone puts on clothing where a spider is trapped.',
    country_top_ten: [
      { country: 'US', rank: 2, danger_summary: 'Cytotoxic venom causes severe dermonecrotic ulceration requiring medical intervention.' }
    ]
  },
  {
    id: 'ixodes-scapularis',
    common_name: 'Deer Tick (Blacklegged Tick)',
    latin_name: 'Ixodes scapularis',
    category: 'Dangerous',
    danger_level: 8,
    can_sting: false,
    can_bite: true,
    dangerous_to_children: true,
    dangerous_to_pets: true,
    regions: ['US', 'CA'],
    active_seasons: ['Spring', 'Summer', 'Autumn'],
    habitat: 'Forest leaf litter, tall grass margins, nature trails, and coastal shrubs.',
    description: 'Ixodes scapularis is a North American tick found primarily in eastern and central parts of the United States and southern Canada. It is an important vector of Lyme disease and can transmit other pathogens including those responsible for babesiosis and Powassan virus. In Europe, the related Castor Bean Tick, Ixodes ricinus, is an important vector of Lyme borreliosis.',
    first_aid: 'Grasp tick close to the skin with fine-point tweezers. Pull straight out firmly without twisting. Disinfect bite site with rubbing alcohol. Note the date of removal.',
    when_to_call_emergency: 'Contact physician promptly if an expanding circular rash (Erythema migrans), fever, facial palsy, or joint inflammation emerges in subsequent weeks.',
    photo_url: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['American Dog Tick (Dermacentor variabilis)', 'Lone Star Tick'],
    fun_fact: 'Tick nymphs are as tiny as a poppy seed (1-2mm), making them easy to overlook without meticulous full-body inspections.',
    country_top_ten: [
      { country: 'US', rank: 1, danger_summary: 'Major tick vector transmitting Lyme disease, Anaplasmosis, and Powassan virus.' },
      { country: 'CA', rank: 1, danger_summary: 'Leading tick vector for Lyme complications across southern Canada.' }
    ]
  },
  {
    id: 'latrodectus-hasselti',
    common_name: 'Redback Spider',
    latin_name: 'Latrodectus hasselti',
    category: 'Venomous',
    danger_level: 9,
    can_sting: false,
    can_bite: true,
    dangerous_to_children: true,
    dangerous_to_pets: true,
    regions: ['AU'],
    active_seasons: ['Summer', 'Autumn', 'Spring'],
    habitat: 'Dry sheltered spots around human dwellings, outdoor furniture, mailboxes, and under plant pots.',
    description: 'Prominent Australian spider with a spherical black body featuring an unmistakable vibrant red or orange longitudinal stripe on the upper abdomen.',
    first_aid: 'Apply an ice pack to relieve intense localized pain. Do not use pressure immobilization (venom acts slowly). Keep calm and transport to medical care.',
    when_to_call_emergency: 'Seek immediate hospital emergency treatment for severe progressive pain, profuse sweating, muscular spasms, or if a child is bitten.',
    photo_url: 'https://images.unsplash.com/photo-1534067783941-51c9c23ecefd?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['Cupboard Spider (Steatoda)', 'Black House Spider'],
    fun_fact: 'Female Redback spiders are up to three times larger than males and frequently consume the male during mating.',
    country_top_ten: [
      { country: 'AU', rank: 2, danger_summary: 'Causes over 2,000 painful envenomations annually treated with Redback antivenom.' }
    ]
  },
  {
    id: 'solenopsis-invicta',
    common_name: 'Red Imported Fire Ant',
    latin_name: 'Solenopsis invicta',
    category: 'Dangerous',
    danger_level: 7,
    can_sting: true,
    can_bite: true,
    dangerous_to_children: true,
    dangerous_to_pets: true,
    regions: ['US', 'AU'],
    active_seasons: ['Spring', 'Summer', 'Autumn'],
    habitat: 'Open sunny pastures, lawns, golf courses, agricultural fields, and electrical utility boxes.',
    description: 'Aggressive reddish-brown ants that construct large dome-shaped earthen mounds. When disturbed, hundreds swarm and sting synchronously, injecting solenopsin alkaloid venom.',
    first_aid: 'Brush ants off vigorously. Wash area with soap. Apply topical hydrocortisone or oral antihistamines to reduce the forming sterile pustules.',
    when_to_call_emergency: 'Call 911 immediately if victim experiences chest tightness, wheezing, hives, or swelling around mouth/throat (anaphylaxis).',
    photo_url: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['Native Harvester Ant', 'Carpenter Ant'],
    fun_fact: 'Fire ants can bind together during flash floods to form a living waterproof floating raft with their queen safely inside.',
    country_top_ten: [
      { country: 'US', rank: 4, danger_summary: 'Red Imported Fire Ants can cause widespread painful stings and envenomation reactions in areas where established colonies occur, particularly across parts of the southern United States.' },
      { country: 'AU', rank: 4, danger_summary: 'High biosecurity priority eradication target in Queensland.' }
    ]
  },
  {
    id: 'tabanus-bovinus',
    common_name: 'Horsefly (Cleg)',
    latin_name: 'Tabanidae sp.',
    category: 'Dangerous',
    danger_level: 6,
    can_sting: false,
    can_bite: true,
    dangerous_to_children: true,
    dangerous_to_pets: true,
    regions: ['UK', 'EU', 'US', 'CA'],
    active_seasons: ['Summer'],
    habitat: 'Damp woodlands, horse stables, lakesides, pastures, and marshlands.',
    description: 'Large, stout-bodied fly with large iridescent eyes. Females have scissor-like mouthparts that slice skin open to pool and drink blood.',
    first_aid: 'Wash the bleeding bite thoroughly with antiseptic wash. Apply cold compress and antihistamine cream to alleviate pain and prominent swelling.',
    when_to_call_emergency: 'Seek medical care if the wound becomes hot, excessively swollen, streaks red (cellulitis), or if allergic symptoms develop.',
    photo_url: 'https://images.unsplash.com/photo-1618828665011-0abd973f7bb8?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['Deer Fly (Chrysops)', 'Robber Fly'],
    fun_fact: 'Horseflies are attracted to dark moving objects, heat signatures, and carbon dioxide exhaled by mammals.',
    country_top_ten: [
      { country: 'UK', rank: 3, danger_summary: 'Causes painful slicing bites frequently complicated by secondary bacterial infections.' }
    ]
  },
  {
    id: 'aedes-albopictus',
    common_name: 'Asian Tiger Mosquito',
    latin_name: 'Aedes albopictus',
    category: 'Dangerous',
    danger_level: 8,
    can_sting: false,
    can_bite: true,
    dangerous_to_children: true,
    dangerous_to_pets: true,
    regions: ['US', 'EU', 'AU'],
    active_seasons: ['Summer', 'Autumn'],
    habitat: 'Urban backyards, flower pot saucers, bird baths, clogged rain gutters, discarded tires.',
    description: 'Distinctive black mosquito with bold white stripes on its body and banded legs. Aggressive daytime biter known as a competent vector for Dengue, Chikungunya, and Zika viruses.',
    first_aid: 'Wash bite with soap and water. Apply calamine lotion or ice pack to soothe itching. Avoid scratching.',
    when_to_call_emergency: 'Consult doctor if high fever, severe joint pain, muscle aches, or rash develop within 3 to 14 days after exposure in endemic zones.',
    photo_url: 'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['Yellow Fever Mosquito (Aedes aegypti)', 'Common House Mosquito (Culex)'],
    fun_fact: 'Female Asian Tiger mosquitoes can successfully lay eggs in very small amounts of standing water, including plant saucers, discarded containers, clogged gutters, and tree hollows.',
    country_top_ten: [
      { country: 'US', rank: 3, danger_summary: 'Major urban disease vector spreading northward due to warming climate.' },
      { country: 'EU', rank: 2, danger_summary: 'Responsible for localized Dengue and Chikungunya outbreaks in Southern and Western Europe.' }
    ]
  },
  {
    id: 'vespula-vulgaris',
    common_name: 'Common Yellowjacket Wasp',
    latin_name: 'Vespula vulgaris',
    category: 'Dangerous',
    danger_level: 7,
    can_sting: true,
    can_bite: true,
    dangerous_to_children: true,
    dangerous_to_pets: true,
    regions: ['UK', 'EU', 'US', 'CA', 'AU'],
    active_seasons: ['Summer', 'Autumn'],
    habitat: 'Underground burrows, wall voids, compost bins, fruit orchards, outdoor picnics.',
    description: 'Bright black and yellow striped social wasp with lance-like smooth stinger capable of delivering repeated venomous stings when defended.',
    first_aid: 'Wash area with antiseptic soap. Apply cold ice pack. Take oral antihistamine and paracetamol/ibuprofen for throbbing pain.',
    when_to_call_emergency: 'Call emergency 911/999/112 if allergic, stung multiple times, or experiencing breathing difficulties or lightheadedness.',
    photo_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['German Wasp (Vespula germanica)', 'Hoverfly (Harmless mimic)'],
    fun_fact: 'In late summer, worker wasps become sugar-cravers and frequently forage around soda cans and sweet drinks.',
    country_top_ten: [
      { country: 'UK', rank: 4, danger_summary: 'Leading source of allergic anaphylaxis stings in late summer picnics.' },
      { country: 'CA', rank: 2, danger_summary: 'Aggressive ground-nesting defender throughout Canadian summers.' }
    ]
  },
  {
    id: 'apis-mellifera',
    common_name: 'Western Honeybee',
    latin_name: 'Apis mellifera',
    category: 'Useful',
    danger_level: 2,
    can_sting: true,
    can_bite: false,
    dangerous_to_children: false,
    dangerous_to_pets: false,
    regions: ['UK', 'US', 'CA', 'AU', 'EU'],
    active_seasons: ['Spring', 'Summer', 'Autumn'],
    habitat: 'Gardens, agricultural orchards, meadows, and managed apiaries.',
    description: 'Indispensable pollinator insect characterized by fuzzy amber-brown coloration and pollen baskets on hind legs. Stings primarily in defense of the hive or when physically compressed, stepped on, or trapped.',
    first_aid: 'Scrape stinger off immediately with a flat card. Wash with soap and water, then ice.',
    when_to_call_emergency: 'Seek urgent emergency medical care if systemic allergic symptoms, breathing difficulties, or swelling of the airway develop.',
    photo_url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['Mason Bee', 'Mining Bee', 'Syrphid Fly'],
    fun_fact: 'Honey bees communicate the location of food sources through the waggle dance. Worker bees are female and perform different roles within the colony, including nursing, guarding and foraging.',
    country_top_ten: []
  },
  {
    id: 'coccinella-septempunctata',
    common_name: 'Seven-Spotted Ladybird',
    latin_name: 'Coccinella septempunctata',
    category: 'Useful',
    danger_level: 0,
    can_sting: false,
    can_bite: false,
    dangerous_to_children: false,
    dangerous_to_pets: false,
    regions: ['UK', 'EU', 'US', 'CA'],
    active_seasons: ['Spring', 'Summer', 'Autumn'],
    habitat: 'Gardens, parks, crop fields, and rose bushes.',
    description: 'Classic beneficial beetle with bright scarlet wing cases and seven distinctive black dots. Natural biocontrol predator of agricultural aphids.',
    first_aid: 'Non-venomous and non-stinging, lacking a venom-delivery apparatus. No specific medical treatment is generally required.',
    when_to_call_emergency: 'None.',
    photo_url: 'https://images.unsplash.com/photo-1535083783855-76ae62b2914e?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['Harlequin Ladybird (Harmonia axyridis)', 'Two-spotted Ladybird'],
    fun_fact: 'Ladybirds reflex-bleed a bitter, foul-tasting yellowish alkaloid fluid from their leg joints to deter predatory birds.',
    country_top_ten: []
  },
  {
    id: 'lucanus-cervus',
    common_name: 'Stag Beetle',
    latin_name: 'Lucanus cervus',
    category: 'Protected',
    danger_level: 1,
    can_sting: false,
    can_bite: true,
    dangerous_to_children: false,
    dangerous_to_pets: false,
    regions: ['UK', 'EU'],
    active_seasons: ['Summer'],
    habitat: 'Ancient oak woodlands, suburban gardens with rotting tree stumps, and parks.',
    description: 'One of the largest terrestrial beetles in Europe and the United Kingdom. Males possess magnificent antler-like mandibles used for wrestling rival males over mates.',
    first_aid: 'Bite from male mandibles is very weak; female can deliver a brief pinch. Wash skin if pinched.',
    when_to_call_emergency: 'None.',
    photo_url: 'https://images.unsplash.com/photo-1618828665011-0abd973f7bb8?auto=format&fit=crop&w=800&q=80',
    look_alikes: ['Lesser Stag Beetle (Dorcus parallelipipedus)'],
    fun_fact: 'Stag beetle larvae develop underground for multiple years, feeding on decaying subterranean hardwood before emerging as adults for the summer breeding season.',
    country_top_ten: []
  },
  {
    id: 'vespa-crabro',
    common_name: 'European Hornet',
    latin_name: 'Vespa crabro',
    category: 'Dangerous',
    danger_level: 6,
    can_sting: true,
    can_bite: true,
    dangerous_to_children: true,
    dangerous_to_pets: true,
    regions: ['UK', 'EU', 'US'],
    active_seasons: ['Spring', 'Summer', 'Autumn'],
    habitat: 'Deciduous woodlands, hollow tree cavities, sheltered eaves, attics, and garden outbuildings.',
    description: 'European hornets are a large native social wasp species found across parts of Europe and established in eastern North America. Workers typically measure around 25–35 mm in length, with queens noticeably larger. They are characterized by a reddish-brown head and anterior thorax, paired with a yellow abdomen patterned with dark lateral spots. European hornets are effective natural predators of various insect species and nest primarily in sheltered cavities.',
    first_aid: 'Wash sting site immediately with soap and water. Apply an ice pack wrapped in a cloth for 15 minutes. Take an over-the-counter antihistamine if swelling occurs. Do NOT attempt to scrape out a stinger unless visibly left behind.',
    when_to_call_emergency: 'Call emergency services (999/911/112) immediately if stung in the mouth or throat, or if signs of anaphylaxis develop (wheezing, lip/tongue swelling, severe dizziness, full-body hives).',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Vespa_crabro_01.jpg/800px-Vespa_crabro_01.jpg',
    look_alikes: ['Asian Hornet (Vespa velutina)', 'Common Yellowjacket (Vespula vulgaris)', 'Cicada Killer'],
    fun_fact: 'European hornets are effective predators of flies, caterpillars, grasshoppers and other insects. Unlike honeybees, they possess a smooth stinger that can be used repeatedly without dying.',
    country_top_ten: [
      { country: 'UK', rank: 6, danger_summary: 'Deep venomous sting, defensive of nest cavities.' },
      { country: 'EU', rank: 4, danger_summary: 'Potent sting with acetylcholine neurotransmitter component.' }
    ]
  }
];

export const TOP_TEN_BY_COUNTRY: Record<string, { rank: number; name: string; latin: string; danger: string; level: number }[]> = {
  UK: [
    { rank: 1, name: 'Castor Bean Tick (Sheep Tick)', latin: 'Ixodes ricinus', danger: 'Primary UK vector for Lyme borreliosis in rural parks and Scottish Highlands.', level: 8 },
    { rank: 2, name: 'Asian Hornet', latin: 'Vespa velutina', danger: 'Invasive predator with intense envenomation risk.', level: 8 },
    { rank: 3, name: 'Horsefly (Cleg)', latin: 'Tabanidae', danger: 'Slices flesh with scissor mandibles, high bacterial infection risk.', level: 6 },
    { rank: 4, name: 'Common Yellowjacket Wasp', latin: 'Vespula vulgaris', danger: 'Multiple aggressive stings, common source of anaphylaxis.', level: 7 },
    { rank: 5, name: 'False Widow Spider', latin: 'Steatoda nobilis', danger: 'Mildly cytotoxic bite resembling a painful wasp sting.', level: 5 },
    { rank: 6, name: 'European Hornet', latin: 'Vespa crabro', danger: 'Deep venomous sting, defensive of nest cavities.', level: 6 },
    { rank: 7, name: 'Oak Processionary Moth (Caterpillar)', latin: 'Thaumetopoea processionea', danger: 'Microscopic barbed hairs cause severe skin/respiratory reactions.', level: 7 },
    { rank: 8, name: 'Biting Midge (Highland Midge)', latin: 'Culicoides impunctatus', danger: 'Relentless swarming biters causing acute dermatitis.', level: 4 },
    { rank: 9, name: 'Bed Bug', latin: 'Cimex lectularius', danger: 'Severe allergic skin welts and sleep disruption.', level: 5 },
    { rank: 10, name: 'German Cockroach', latin: 'Blattella germanica', danger: 'Major household allergen trigger and disease carrier.', level: 5 }
  ],
  US: [
    { rank: 1, name: 'Deer Tick (Blacklegged Tick)', latin: 'Ixodes scapularis', danger: 'Vector for Lyme disease, Anaplasmosis, and Powassan.', level: 8 },
    { rank: 2, name: 'Brown Recluse Spider', latin: 'Loxosceles reclusa', danger: 'Potent cytotoxic venom causing necrotic tissue breakdown.', level: 9 },
    { rank: 3, name: 'Western Black Widow Spider', latin: 'Latrodectus hesperus', danger: 'Neurotoxic alpha-latrotoxin causing severe muscle rigidity.', level: 9 },
    { rank: 4, name: 'Red Imported Fire Ant', latin: 'Solenopsis invicta', danger: 'Swarming mass stings causing pustules and anaphylaxis.', level: 7 },
    { rank: 5, name: 'Asian Tiger Mosquito', latin: 'Aedes albopictus', danger: 'Competent vector for Dengue, West Nile, and Zika.', level: 8 },
    { rank: 6, name: 'Africanized Honey Bee', latin: 'Apis mellifera scutellata', danger: 'Hyper-defensive "killer bees" pursuing victims for hundreds of yards.', level: 8 },
    { rank: 7, name: 'Striped Bark Scorpion', latin: 'Centruroides vittatus', danger: 'Neurotoxic stings in southwest/southern states.', level: 7 },
    { rank: 8, name: 'Puss Caterpillar (Southern Flannel Moth)', latin: 'Megalopyge opercularis', danger: 'Venomous spines cause agonizing bone-deep burning pain.', level: 8 },
    { rank: 9, name: 'Bald-faced Hornet', latin: 'Dolichovespula maculata', danger: 'Aggressive nest defender with smooth repeat stinger.', level: 7 },
    { rank: 10, name: 'Kissing Bug (Triatominae)', latin: 'Triatoma sp.', danger: 'Vector for Chagas disease parasite in southern regions.', level: 7 }
  ],
  AU: [
    { rank: 1, name: 'Sydney Funnel-Web Spider', latin: 'Atrax robustus', danger: 'World’s most dangerous spider; lethal without antivenom.', level: 10 },
    { rank: 2, name: 'Redback Spider', latin: 'Latrodectus hasselti', danger: 'Common suburban venomous spider causing intense systemic latrodectism.', level: 9 },
    { rank: 3, name: 'Bull Ant (Myrmecia)', latin: 'Myrmecia gulosa', danger: 'Largest ants on Earth; jumps and stings with allergenic venom.', level: 8 },
    { rank: 4, name: 'Australian Paralysis Tick', latin: 'Ixodes holocyclus', danger: 'Secretes holocyclotoxin causing ascending motor paralysis.', level: 9 },
    { rank: 5, name: 'Mouse Spider', latin: 'Missulena sp.', danger: 'Deep venomous bite comparable to Funnel-webs.', level: 8 },
    { rank: 6, name: 'Red Imported Fire Ant', latin: 'Solenopsis invicta', danger: 'Invasive agricultural and health biosecurity hazard.', level: 7 },
    { rank: 7, name: 'Paper Wasp', latin: 'Polistes sp.', danger: 'Defensive suburban stinging wasps.', level: 6 },
    { rank: 8, name: 'March Fly (Australian Tabanid)', latin: 'Tabanidae', danger: 'Painful slicing bite with prolonged bleeding.', level: 5 },
    { rank: 9, name: 'Centipede (Giant Centipede)', latin: 'Ethmostigmus rubripes', danger: 'Painful venomous forcipules causing burning swelling.', level: 7 },
    { rank: 10, name: 'White-tailed Spider', latin: 'Lampona cylindrata', danger: 'Painful localized bite often causing secondary irritation.', level: 5 }
  ],
  CA: [
    { rank: 1, name: 'Blacklegged Tick', latin: 'Ixodes scapularis', danger: 'Spreading Lyme disease across Ontario, Quebec, and Maritimes.', level: 8 },
    { rank: 2, name: 'Yellowjacket Wasp', latin: 'Vespula vulgaris', danger: 'Ground-dwelling late summer stinging menace.', level: 7 },
    { rank: 3, name: 'Northern Black Widow Spider', latin: 'Latrodectus variolus', danger: 'Rare but present in southern Ontario and Okanagan.', level: 8 },
    { rank: 4, name: 'Horsefly & Deerfly', latin: 'Tabanidae', danger: 'Aggressive biters near Canadian shield lakes.', level: 6 },
    { rank: 5, name: 'Black Flies (Simuliidae)', latin: 'Simulium sp.', danger: 'Massive swarms in northern boreal forests causing blood loss.', level: 5 },
    { rank: 6, name: 'Bald-faced Hornet', latin: 'Dolichovespula maculata', danger: 'Large aerial paper nests with defensive stinging.', level: 7 },
    { rank: 7, name: 'Bed Bug', latin: 'Cimex lectularius', danger: 'Widespread metropolitan pest problem.', level: 5 },
    { rank: 8, name: 'Bumblebee', latin: 'Bombus sp.', danger: 'Docile pollinator, but stings if crushed or nest disturbed.', level: 3 },
    { rank: 9, name: 'Mosquito (Culex tarsalis)', latin: 'Culex tarsalis', danger: 'Vector for West Nile Virus across the Prairies.', level: 6 },
    { rank: 10, name: 'European Paper Wasp', latin: 'Polistes dominula', danger: 'Invasive wasp nesting under residential roof eaves.', level: 5 }
  ],
  EU: [
    { rank: 1, name: 'Castor Bean Tick (Sheep Tick)', latin: 'Ixodes ricinus', danger: 'Primary vector for Lyme disease and Tick-Borne Encephalitis (TBE).', level: 8 },
    { rank: 2, name: 'Asian Tiger Mosquito', latin: 'Aedes albopictus', danger: 'Dengue and Chikungunya transmission in Mediterranean and Western Europe.', level: 8 },
    { rank: 3, name: 'Asian Hornet', latin: 'Vespa velutina', danger: 'Invasive species responsible for severe anaphylactic emergencies.', level: 8 },
    { rank: 4, name: 'European Hornet', latin: 'Vespa crabro', danger: 'Potent sting with acetylcholine neurotransmitter component.', level: 6 },
    { rank: 5, name: 'European Black Widow (Mediterranean Widow)', latin: 'Latrodectus tredecimguttatus', danger: 'Venomous spider with 13 red spots found in Southern Europe.', level: 8 },
    { rank: 6, name: 'Pine Processionary Caterpillar', latin: 'Thaumetopoea pityocampa', danger: 'Extremely dangerous urticating hairs causing necrosis in dogs and humans.', level: 8 },
    { rank: 7, name: 'European Yellowjacket', latin: 'Vespula germanica', danger: 'Aggressive picnic scavenger and nest defender.', level: 7 },
    { rank: 8, name: 'Mediterranean Recluse Spider', latin: 'Loxosceles rufescens', danger: 'Cytotoxic bite with necrotic potential in Mediterranean basin.', level: 7 },
    { rank: 9, name: 'Horsefly (Tabanus)', latin: 'Tabanus bovinus', danger: 'Painful blood-sucking bite near livestock and water.', level: 6 },
    { rank: 10, name: 'Yellow-tailed Scorpion', latin: 'Tetratrichobothrius flavicaudis', danger: 'Mildly venomous scorpion found in Southern Europe and UK docks.', level: 5 }
  ]
};
